# Generated by Django 3.2 on 2021-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_aboutbusiness_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstaff',
            name='year',
            field=models.FloatField(default=0.0, verbose_name='Total Salary Paid per Year'),
        ),
    ]
