# Generated by Django 3.2 on 2021-04-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_businessdocument_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdocument',
            name='document',
            field=models.ImageField(null=True, upload_to='documents/', verbose_name='Passport Phpassotography'),
        ),
    ]
