# Generated by Django 3.2 on 2021-05-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_businessdocument_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdocument',
            name='title',
        ),
    ]
